### ISSUE TITLE
Iemand zou een intro moeten schrijven (zonder titeltje)

### ISSUE THREAD

**Issue by yofWeHan4** [yofWeHan4/Wisselbeker-Bernard-Verbeke#2]
Vlak na de hoofdtitel zou een tekstje moeten komen dat wat kadering geeft over de wisselbeker en historie

**Comment by dvanderfaeillie** [comment]
Damn, you've been busy.
Controle staat op mijn todo list

**Comment by tdebusschere** [comment]
ok

**Comment by yofWeHan4** [comment]
Ipv forken (onnodig) heb je toegevoegd als collaborator

On February 17, 2016 10:16:57 AM GMT+01:00, "tdebusschere [Masked]" <FWD-737QTYSMENAIYCQANIQDDYAOMQDOAIZBDRCCB3AMHVAFCTJAFQQQ3MDCNEAXQIBCGRDQ563XZRASIULLHVMGY3RAIMADGEFADGRBJJBURAR7WRRUEDVBAMDGU5IKQHCCCUKXI2KQEAFKIQVAA5QA5AAJQABQAAMABMDC5ECALVAE2QBXDSPBKYT4KQHDAABAAAQA====@opayq.com> wrote:

> ---------------------Blur (formerly DoNotTrackMe)---------------------
> This email is forwarded from a MASKED EMAIL you created using Blur
> (formerly DoNotTrackMe).  (https://dnt.abine.com/help).
> IF THIS IS SPAM, CLICK HERE TO BLOCK:
> https://dnt.abine.com/#/block_email/f794c713@opayq.com/FWD-737QTYSMENAIYCQANIQDDYAOMQDOAIZBDRCCB3AMHVAFCTJAFQQQ3MDCNEAXQIBCGRDQ563XZRASIULLHVMGY3RAIMADGEFADGRBJJBURAR7WRRUEDVBAMDGU5IKQHCCCUKXI2KQEAFKIQVAA5QA5AAJQABQAAMABMDC5ECALVAE2QBXDSPBKYT4KQHDAABAAAQA====@opayq.com
> 
> Want to shop safely and privately online? Go Premium:
> https://dnt.abine.com/?pk_campaign=maskHeader#premium
> -------------------------by Abine-------------------------
> 
> ok
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yofWeHan4/Wisselbeker-Bernard-Verbeke/issues/2#issuecomment-185110635

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yofWeHan4** [comment]
Niet nodig om te forken, ik heb je toegevoegd als collaborator. Als project altijd zoveel mogelijk forken vermeiden want dan krijg je complete versnippering 

----- Original Message -----

**Comment by tdebusschere** [comment]
ik moet toch de aandacht trekken e :P

**Comment by yofWeHan4** [comment]
Typisch :p 

----- Original Message -----

**Comment by tdebusschere** [comment]
Lol

**Comment by dvanderfaeillie** [comment]
@tdebusschere 
Wat moet het onderstaande voorstellen? Living in obscurity, masked mail, stefan2?
_This email is forwarded from a MASKED EMAIL you created using DoNotTrackMe . IF THIS IS SPAM, CLICK HERE TO BLOCK. Want to shop safely and privately online? Get DoNotTrackMe Premium ._

Keep the mailing list clean please

**Comment by yofWeHan4** [comment]
Dat is om te voorkomen dat julie mijn echte identiteit achterhalen. 
We have been over this already, btw 

----- Original Message -----
