### ISSUE TITLE
Uitbreiding van het organiserend committee

### ISSUE THREAD

**Issue by DenDikken** [yofWeHan4/Wisselbeker-Bernard-Verbeke#3]
Procedure hieromtrent is niet beschreven.

**Comment by dvanderfaeillie** [comment]
-1

**Comment by yofWeHan4** [comment]
Unanimiteit van het organiserende comité is nodig

**Comment by yofWeHan4** [comment]
Answer: Unanimiteit van het organiserende comité is nodig
